version: '3.8'

services:
  api:
    build:
      context: ..
      dockerfile: environment/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URL=mongodb://mongodb:27017
      - PYTHONPATH=/app
    depends_on:
      - mongodb
    volumes:
      - ../app:/app/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 